# Generated by Django 6.0.7 on 2026-07-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('matricule', models.CharField(max_length=50, verbose_name='Matricule Number')),
                ('school', models.CharField(max_length=200, verbose_name='School/Faculty')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone Number (for updates)')),
                ('complaint_number', models.CharField(max_length=100, verbose_name='Complaint Number')),
                ('submission_office', models.CharField(help_text="e.g., Dean's Office, Department of Physics, Exams and Records", max_length=300, verbose_name='Which office should we submit this to?')),
                ('complaint_text', models.TextField(help_text='Describe your issue clearly', verbose_name='What is your complaint about?')),
                ('course', models.CharField(max_length=200, verbose_name='Course Title')),
                ('course_code', models.CharField(max_length=50, verbose_name='Course Code')),
                ('ca_mark', models.CharField(max_length=50, verbose_name='CA Mark')),
                ('exam_mark', models.CharField(max_length=50, verbose_name='Exam Mark')),
                ('proof', models.FileField(help_text='Upload any relevant document or screenshot', upload_to='proofs/', verbose_name='Supporting Document/Proof')),
                ('payment_screenshot', models.ImageField(blank=True, help_text='Upload screenshot of your MoMo payment confirmation', null=True, upload_to='payment_proofs/', verbose_name='Payment Screenshot')),
                ('payment_status', models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Paid - Awaiting Verification'), ('verified', 'Payment Verified')], default='pending', max_length=20, verbose_name='Payment Status')),
                ('is_submitted', models.BooleanField(default=False, verbose_name='Submitted to Office?')),
                ('submitted_snapshot', models.ImageField(blank=True, null=True, upload_to='submitted_forms/', verbose_name='Submitted Form Snapshot')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Complaint',
                'verbose_name_plural': 'Complaints',
                'ordering': ['-created_at'],
            },
        ),
    ]
