# Generated by Django 6.0.7 on 2026-07-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='level',
            field=models.CharField(default='unknown', help_text='e.g., 100, 200, 300, 400, Masters', max_length=50, verbose_name='Level'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaint',
            name='semester',
            field=models.CharField(default='unknown', help_text='e.g., First Semester, Second Semester', max_length=20, verbose_name='Semester'),
            preserve_default=False,
        ),
    ]
